apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sknf
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: sknf
  template:
    metadata:
      labels:
        app: sknf
    spec:
      serviceAccountName: sknf
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoSchedule"

      # ensure pods run on control-plane nodes too
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"

      containers:
      - name: sknf
        image: sknf
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
          runAsUser: 0
          runAsGroup: 0
          allowPrivilegeEscalation: true
          readOnlyRootFilesystem: false
        volumeMounts:
        - name: host-cni-bin
          mountPath: /host/opt/cni/bin
        - name: host-cni-conf
          mountPath: /host/etc/cni/net.d
        env:
        - name: CNI_PLUGIN_BINARY_CONTAINER_PATH_ENV_KEY
          value: /home/sknf/sknf-cni/bin/sknf-cni
        - name: CNI_PLUGIN_CONF_CONTAINER_PATH_ENV_KEY
          value: /home/sknf/sknf-cni/conf/sknf-cni-conf.json
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName

      volumes:
      - name: host-cni-bin
        hostPath:
          path: /opt/cni/bin
          type: Directory
      - name: host-cni-conf
        hostPath:
          path: /etc/cni/net.d
          type: DirectoryOrCreate
